### ISSUE TITLE
Last step - unclear

### ISSUE THREAD

**Issue by milosb793** [jesalg/SlimJim#15]
Hello there! :) 

Firstly, thanks for the tool, it's looking promising! I was about to test it, and got it all except the last step. What should I do exactly in this step: 

```
Add Post-Receive Webhook
Finally, add the appropriate one of these URLs as a webhook into your repository settings:

For GitHub: http://slimjim.yourcompany.com/gh_hook

For BitBucket: http://slimjim.yourcompany.com/bb_hook
```
? 

Where should I add the https://mysite/gh_hook? 

Thanks in further!

**Comment by jesalg** [comment]
@milosb793 You'd add that in the repo's webhook settings. So for GitHub it would be here: 

![image](https://user-images.githubusercontent.com/885248/80290648-93a1f700-86fb-11ea-9e15-1ce98ecc0b4b.png)

Hope that helps!

**Comment by milosb793** [comment]
Yeah, that's it! Thank you very much!
