### ISSUE TITLE
deploy.php fails with parse error: syntax error unexpected ':' 

### ISSUE THREAD

**Issue by stevies** [jesalg/SlimJim#3]
Deploy script fails with: 

Parse error: syntax error, unexpected ':' in /home/xxx/deploy.php on line 32

Running on Apache 2.2.6.  PHP 5.2.5.

**Comment by stevies** [comment]
Ah - I see that the Slim framework requires PHP 5.3.  So, I can't use SlimJim.  Spent hours on this - my fault for not checking.  But it might be nice to show minimum system requirements in the SlimJim project docs.

**Comment by jesalg** [comment]
Good point, I'll add that to the readme.
