### ISSUE TITLE
not working in subdirectory of website

### ISSUE THREAD

**Issue by johnmolino** [jesalg/SlimJim#5]
From my testing, (at least for the Admin area), the pathing doesn't seem to work correctly when setup in a subdirectory off the server root. (i.e. http://mysite.com/slimjim/admin/index.php ) .

When I did a subdomain w/ slimjim in the root it worked fine....(i.e. http://mysite.com/admin/index.php )

This possibly could have been my server configuration - so this is an unverified issue.

(Centos 5 / apache 2 / php 5.3 )

**Comment by jesalg** [comment]
Ah ok that's because it assumes this site will run off the root. I need to define something like this at the top:

```
define( "APP_ROOT", realpath( dirname( __FILE__ ) ).'/' );
```

And use that in all the paths:

```
require_once( APP_ROOT.'../../path/to/file.php' );
```

I'll commit a fix for that

**Comment by johnmolino** [comment]
OK great thanks! I did end up just running this as you do, in a root of a
subdomain, so this isn't affecting me anymore, but its' good to get the
changes in for others.

As a side note, I notice in the deploy.php there is some reference to
additional commands you can run "after_deploy" for instance... but I didn't
see any reference to this in the README

Do you have any information on how to use this?

Thanks,
John

**Comment by jesalg** [comment]
That's a feature contributed by @animecyc which adds the ability to run commands after the repo is updated and/or make file/folders writable. 

More info about that feature here: https://github.com/jesalg/SlimJim/pull/1
